name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
categories:
  - title: 'Mudanças incompatíveis'
    label: 'breaking-change'
  - title: 'Bugs Resolvidos'
    label: 'bug'
  - title: 'Novas Features'
    label: 'feature'
  - title: 'Documentação'
    label: 'docs'
version-resolver:
  minor:
    labels:
      - 'breaking-change'
  patch:
    labels:
      - 'feature'
      - 'bug'
template: |
  ## Changelog for $RESOLVED_VERSION

  $CHANGES

  **Como atualizar para $RESOLVED_VERSION**: https://async-worker.github.io/async-worker/changelog/v$RESOLVED_VERSION.html
  Docs: https://async-worker.github.io/async-worker/
  Commits: https://github.com/async-worker/async-worker/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
