{
 "title": "Asyncworker HTTP Routes",
 "description": "Metrics visualization for asyncworker automatically exposed metrics",
 "tags": [ "async-worker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "path", "label": "Path", "query": { "query": "label_values(path)" } },
   { "name": "method", "label": "Method", "query": { "query": "label_values(method)" } },
   { "name": "status", "label": "Response status code", "query": { "query": "label_values(status)" } },
   { "name": "error_code", "label": "Status code 4xx or 5xx", "query": { "query": "label_values(status)" } }
  ]
 },
 "panels": [
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(asyncworker_http_request_duration_ms_sum{path=~\"$path\", instance=~\"$instance\"}[$__interval]) / rate(asyncworker_http_request_duration_ms_count{path=~\"$path\", instance=~\"$instance\"}[$__interval])\n",
     "legendFormat": "{{path}} - avg"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(asyncworker_http_request_duration_ms_bucket{path=~\"$path\",instance=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "99th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(asyncworker_http_request_duration_ms_bucket{path=~\"$path\",instance=~\"$instance\",method=~\"$method\",status=~\"$status\"}[$__interval])) by (le, path))\n\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests over 100ms",
   "type": "graph",
   "description": "Percentage of requests served over 100ms",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(asyncworker_http_request_duration_ms_bucket{le=\"100.0\",path=~\"$path\",instance=~\"$instance\",status=~\"$status\"}[$__interval])) by (path)\n/\nsum(rate(asyncworker_http_request_duration_ms_count{path=~\"$path\",instance=~\"$instance\",status=~\"$status\"}[$__interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Requests per minute (RPM)",
   "type": "graph",
   "description": "Number of request served per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(asyncworker_http_request_duration_ms_count{path=~\"$path\",instance=~\"$instance\",status=~\"$status\"}[$__interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Errors per minute (RPM)",
   "type": "graph",
   "description": "Number of requests served per minute wich resulted in 4xx or 5xx status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(asyncworker_http_request_duration_ms_count{path=~\"$path\",instance=~\"$instance\",status=~\"$error_code\"}[$__interval])",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests in progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(asyncworker_http_requests_in_progress{path=~\"$path\", method=~\"$method\",instance=~\"$instance\"}[$__interval])\n",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "Response size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Average response size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(asyncworker_http_response_size_bytes_sum{path=~\"$path\", instance=~\"$instance\"}[$__interval]) / rate(asyncworker_http_response_size_bytes_count{path=~\"$path\", instance=~\"$instance\"}[$__interval])\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP response size histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(asyncworker_http_response_size_bytes_bucket{path=~\"$path\",instance=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}