{
 "title": "Asyncworker Python Process",
 "description": "Metrics related to the python process and resource usage like CPU, RAM, Garbage Collection, file descriptors and others",
 "tags": [ "async-worker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "pod",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - asyncworker_process_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(asyncworker_process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "asyncworker_process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Python Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "name",
   "targets": [
    {
     "expr": "asyncworker_python_info{instance=~\"$instance\"}",
     "legendFormat": "{{implementation}} {{version}}"
    }
   ]
  },
  {
   "title": "Max file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "asyncworker_process_max_fds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(asyncworker_process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "graph",
   "description": "Number of objects collected during gc.\t",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(asyncworker_python_gc_objects_collected_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "collected - gen {{ generation }}"
    }
   ]
  }
 ]
}