name: release

on:
  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pip
        run: pip install -U pip

      - name: Install twine
        run: pip install twine==6.1.0

      - name: Generate Packages
        run: python setup.py sdist

      - name: Twine check
        run: twine check dist/*

      - name: Publish (${{github.ref}})
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
        run: twine upload dist/*
